model_list:
  - model_name: fake-openai-endpoint
    litellm_params:
      model: openai/my-fake-model
      api_key: my-fake-key
      api_base: https://exampleopenaiendpoint-production.up.railway.app/

litellm_settings:
  cache: True
  cache_params:
    type: redis
    redis_startup_nodes:
      - host: redis0.cl
        port: 10001
      - host: redis1.cl
        port: 10001
      - host: redis2.cl
        port: 10001
